### PR TITLE
Segmentation

### PR DESCRIPTION
**Pull request by john-rocky**
Segmentation feature has been added.
If you add a segment model and select seg in the task, you can view the segment mask in real time.

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
This update enhances the Ultralytics YOLO iOS app by improving model handling, adding segmentation and human tracking tasks, refining the UI, and updating model management.

### 📊 Key Changes
- **Model Management**: Implemented logic to switch between different YOLOv8 models (n, s, m, l, x) for various tasks (detection, segmentation, human tracking).
- **UI and UX Improvements**: Added new segment controls and updates to manage tasks and thresholds better in different screen orientations.
- **New Functionalities**:
  - **Segmentation**: Integration of post-processing for displaying segment masks.
  - **Human Tracking**: Detection and tracking of individual human features over multiple frames.
- **Performance Enhancements**: Improved video capture with appropriate orientation handling, enhanced bounding box display, and added inner text layering for detailed object information.
- **Code Simplification**: Streamlined model setup and bounding box view initialization.
- **Documentation Updates**: Updated README and Info.plist.

### 🎯 Purpose & Impact
- **User Experience**: Enhanced interaction with new controls for task management and better orientation handling, ensuring the app is more intuitive and user-friendly.
- **Functionality**: Expanded capabilities to include segmentation and persistent human tracking, offering more comprehensive analysis tools.
- **Performance**: Improved video feed handling and bounding box display ensures smoother app performance and more accurate data representation.
- **Code Maintenance**: Simplified codebase contributes to easier updates and debugging, fostering a more efficient development process.

### CODE REVIEW

**Comment by john-rocky** [comment]
Changed the colors of the segment mask and detection box to the same Ultralytics color palette as the Python version.
Also removed the central focus square.

**Comment by pderrenger** [comment]
Thank you for your contribution! 🎉 It's great to see enhancements that align the iOS app's visual elements with the Python version's color palette. This consistency can significantly improve the user experience.

If you encounter any issues or have further suggestions, please ensure you are using the latest version of the Ultralytics packages. If the issue persists, providing a minimum reproducible example can greatly help us diagnose and address the problem more efficiently. You can find more details on how to create one here: [Minimum Reproducible Example](https://docs.ultralytics.com/help/minimum_reproducible_example).

Keep up the great work, and thank you for helping improve the Ultralytics community! 🚀

**Comment by pderrenger** [comment]
@john-rocky thank you for sharing your update! It's great to see the alignment of the segment mask and detection box colors with the Ultralytics color palette. This consistency will definitely enhance the user experience.

If you encounter any issues or have further questions, please ensure you're using the latest version of the Ultralytics packages. This helps us ensure that any bugs or issues are addressed with the most recent fixes and improvements.

If you need any additional guidance or run into any challenges, feel free to ask. We're here to help! 😊

Keep up the great work!

**Review by ambitious-octopus — CHANGES_REQUESTED** [review]
Hey @john-rocky , this is the next one to close. Here we need to resolve conflicts and remove all references to YOLO Human. We also need to sync this branch with main and as with the other PRs add references to the model and fix the package versions in the `.storyboard` files. We also need to remove the `.png` files and consequently the `Contents.json` file.

**Comment by john-rocky** [comment]
@ambitious-octopus 
I created a new seg branch to merge segmentation into main.
I removed the human feature and aligned the reference to the model and the version to main.
https://github.com/ultralytics/yolo-ios-app/pull/58

**Review by ambitious-octopus — COMMENTED** [review]
@john-rocky Can we close this PR in favor of PR #58, which resolves the merge conflicts? In the future, please try to keep everything consolidated in a single PR. Thanks!

**Comment by john-rocky** [comment]
@ambitious-octopus 
This PR is closed.
It would have been time-consuming and complicated to keep only the segmentation feature and remove the other features, so for this time only I created a simple version in a separate branch that simply added the feature.
From now on, I will add only one feature per branch, so that they can be integrated with one PR.

**Review by ambitious-octopus — COMMENTED** [review]
@john-rocky Thanks for that, closed in favor of #58!

**Pull request closed without merging**
